export function createCanonicalUnarmedAttack(attack = {}, fighter = {}) {
  const damage = fighter?.unarmedDamage || "1d3";
  return {
    ...attack,
    id: "natural.unarmed",
    weaponId: "natural.unarmed",
    profileKey: "natural.unarmed",
    name: "Unarmed Attack",
    damage,
    damageDice: damage,
    damageType: "blunt",
    count: Number(attack?.count ?? 1),
    type: "melee",
    attackType: "melee",
    weaponType: "melee",
    category: "melee",
    handedness: "unarmed",
    handsRequired: 0,
    requiresTwoHands: false,
    twoHanded: false,
    range: 5,
    rangeFeet: 5,
    reachFeet: 5,
    isRanged: false,
    isMelee: true,
    isNaturalAttack: true,
    naturalWeapon: true,
    manufacturedWeapon: false,
    isFallbackUnarmed: true,
    sourceWeapon: null,
    sourceWeaponSnapshot: null,
    sourceWeaponId: "Unarmed Attack",
    sourceWeaponName: "Unarmed Attack",
    originalWeaponName: "Unarmed Attack",
    armoredActionPlan: null,
    selectedTechnique: null,
    armorTechnique: null,
    armorTechniqueCompatibility: [],
    retainedInClinch: false,
    usableInClinch: true,
    groundedCompatible: true,
    attackMode: "unarmed",
  };
}

export default createCanonicalUnarmedAttack;
