import { getPropGameplayProfile } from "./propCapabilityCatalog.js";

const prop = ({
  type,
  label,
  category,
  heightFeet = 3,
  cover = 0,
  blocksMovement = false,
  blocksLineOfSight = false,
  lightSource = null,
  localAtmosphere = null,
} = {}) => Object.freeze({
  type,
  label,
  category,
  heightFeet,
  cover,
  blocksMovement,
  blocksLineOfSight,
  ...(lightSource ? { lightSource: Object.freeze(lightSource) } : {}),
  ...(localAtmosphere ? { localAtmosphere: Object.freeze(localAtmosphere) } : {}),
  gameplay: Object.freeze(getPropGameplayProfile(type)),
});

export const EXPANDED_BATTLEFIELD_PROP_DEFINITIONS = Object.freeze({
  table: prop({ type: "table", label: "Table", category: "furnishing", heightFeet: 3, cover: 1, blocksMovement: true }),
  chair: prop({ type: "chair", label: "Chair", category: "furnishing", heightFeet: 3 }),
  bench: prop({ type: "bench", label: "Bench", category: "furnishing", heightFeet: 3, cover: 1 }),
  stool: prop({ type: "stool", label: "Stool", category: "furnishing", heightFeet: 2 }),
  bed: prop({ type: "bed", label: "Bed", category: "furnishing", heightFeet: 3, blocksMovement: true }),
  chest: prop({ type: "chest", label: "Chest", category: "furnishing", heightFeet: 3, cover: 1, blocksMovement: true }),
  barrel: prop({ type: "barrel", label: "Barrel", category: "furnishing", heightFeet: 4, cover: 1, blocksMovement: true }),
  keg: prop({ type: "keg", label: "Keg", category: "furnishing", heightFeet: 3, cover: 1 }),
  "grain-sack": prop({ type: "grain-sack", label: "Grain Sack", category: "furnishing", heightFeet: 3 }),
  basket: prop({ type: "basket", label: "Basket", category: "furnishing", heightFeet: 2 }),
  "bar-counter": prop({ type: "bar-counter", label: "Bar Counter", category: "furnishing", heightFeet: 4, cover: 2, blocksMovement: true }),
  hearth: prop({
    type: "hearth", label: "Hearth", category: "light", heightFeet: 4, blocksMovement: true,
    lightSource: { radiusFeet: 30, intensity: 0.72, color: "#ff9b55", flicker: true },
    localAtmosphere: { type: "smoke", radiusFeet: 6, occlusion: 0.08 },
  }),
  shelf: prop({ type: "shelf", label: "Shelf", category: "furnishing", heightFeet: 6, blocksMovement: true }),
  cupboard: prop({ type: "cupboard", label: "Cupboard", category: "furnishing", heightFeet: 6, blocksMovement: true }),
  "weapon-rack": prop({ type: "weapon-rack", label: "Weapon Rack", category: "furnishing", heightFeet: 6, cover: 1, blocksMovement: true }),
  "armor-stand": prop({ type: "armor-stand", label: "Armor Stand", category: "furnishing", heightFeet: 6, blocksMovement: true }),
  altar: prop({ type: "altar", label: "Altar", category: "furnishing", heightFeet: 4, cover: 2, blocksMovement: true }),
  "candle-stand": prop({
    type: "candle-stand", label: "Candle Stand", category: "light", heightFeet: 5,
    lightSource: { radiusFeet: 12, intensity: 0.28, color: "#ffd49a", flicker: true },
  }),
  cage: prop({ type: "cage", label: "Iron Cage", category: "structure", heightFeet: 8, cover: 2, blocksMovement: true }),
  chain: prop({ type: "chain", label: "Chain", category: "furnishing", heightFeet: 5 }),
  lever: prop({ type: "lever", label: "Lever", category: "furnishing", heightFeet: 4 }),
  "pressure-plate": prop({ type: "pressure-plate", label: "Pressure Plate", category: "furnishing", heightFeet: 0 }),
  trapdoor: prop({ type: "trapdoor", label: "Trapdoor", category: "structure", heightFeet: 0 }),
  portcullis: prop({ type: "portcullis", label: "Portcullis", category: "structure", heightFeet: 12, cover: 3, blocksMovement: true, blocksLineOfSight: false }),
  chandelier: prop({
    type: "chandelier", label: "Chandelier", category: "light", heightFeet: 8,
    lightSource: { radiusFeet: 28, intensity: 0.55, color: "#ffd18b", flicker: true },
  }),
  brazier: prop({
    type: "brazier", label: "Brazier", category: "light", heightFeet: 4, blocksMovement: true,
    lightSource: { radiusFeet: 35, intensity: 0.72, color: "#ff9b55", flicker: true },
    localAtmosphere: { type: "smoke", radiusFeet: 7, occlusion: 0.1 },
  }),
  well: prop({ type: "well", label: "Village Well", category: "structure", heightFeet: 4, cover: 2, blocksMovement: true }),
  "market-stall": prop({ type: "market-stall", label: "Market Stall", category: "furnishing", heightFeet: 7, cover: 2, blocksMovement: true }),
  signpost: prop({ type: "signpost", label: "Signpost", category: "furnishing", heightFeet: 7 }),
  wagon: prop({ type: "wagon", label: "Wagon", category: "furnishing", heightFeet: 7, cover: 3, blocksMovement: true }),
  "hay-bale": prop({ type: "hay-bale", label: "Hay Bale", category: "furnishing", heightFeet: 3, cover: 1, blocksMovement: true }),
  haystack: prop({ type: "haystack", label: "Haystack", category: "natural", heightFeet: 8, cover: 2, blocksMovement: true }),
  wheat: prop({ type: "wheat", label: "Wheat", category: "natural", heightFeet: 4 }),
  barley: prop({ type: "barley", label: "Barley", category: "natural", heightFeet: 4 }),
  cabbage: prop({ type: "cabbage", label: "Cabbage", category: "natural", heightFeet: 1 }),
  vineyard: prop({ type: "vineyard", label: "Vine Row", category: "natural", heightFeet: 5, cover: 1, blocksMovement: true }),
  "apple-tree": prop({ type: "apple-tree", label: "Apple Tree", category: "natural", heightFeet: 18, cover: 2, blocksMovement: true, blocksLineOfSight: true }),
  stump: prop({ type: "stump", label: "Tree Stump", category: "natural", heightFeet: 3, cover: 1, blocksMovement: true }),
  "fallen-log": prop({ type: "fallen-log", label: "Fallen Log", category: "natural", heightFeet: 4, cover: 2, blocksMovement: true }),
  barricade: prop({ type: "barricade", label: "Barricade", category: "structure", heightFeet: 5, cover: 3, blocksMovement: true, blocksLineOfSight: false }),
  mantlet: prop({ type: "mantlet", label: "Mantlet", category: "structure", heightFeet: 7, cover: 3, blocksMovement: true, blocksLineOfSight: true }),
  stakes: prop({ type: "stakes", label: "Defensive Stakes", category: "structure", heightFeet: 4, cover: 1, blocksMovement: true, blocksLineOfSight: false }),
  ladder: prop({ type: "ladder", label: "Ladder", category: "structure", heightFeet: 12 }),
  banner: prop({ type: "banner", label: "Banner", category: "furnishing", heightFeet: 10 }),
  "ammo-crate": prop({ type: "ammo-crate", label: "Ammunition Crate", category: "furnishing", heightFeet: 4, cover: 1, blocksMovement: true }),
  corpse: prop({ type: "corpse", label: "Corpse", category: "furnishing", heightFeet: 1 }),
  rowboat: prop({ type: "rowboat", label: "Rowboat", category: "furnishing", heightFeet: 3, blocksMovement: true }),
  raft: prop({ type: "raft", label: "Raft", category: "furnishing", heightFeet: 2, blocksMovement: true }),
  dock: prop({ type: "dock", label: "Dock Section", category: "structure", heightFeet: 2, blocksMovement: false }),
  "mooring-post": prop({ type: "mooring-post", label: "Mooring Post", category: "structure", heightFeet: 4, blocksMovement: true }),
  key: prop({ type: "key", label: "Quest Key", category: "furnishing", heightFeet: 0 }),
  document: prop({ type: "document", label: "Document", category: "furnishing", heightFeet: 0 }),
  "coin-purse": prop({ type: "coin-purse", label: "Coin Purse", category: "furnishing", heightFeet: 0 }),
});

export default EXPANDED_BATTLEFIELD_PROP_DEFINITIONS;
